car/carpool/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

car/driver/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from . import views

app_name = 'driver'

urlpatterns = [
    url(r'^(?P<username>[-_\w.]+)$', views.home, name='home'),
    url(r'^profile/(?P<username>[-_\w.]+)$',
        views.profile, name='profile_view'),
    url(r'^profile/(?P<username>[-_\w.]+)/update/$',
        views.update_profile, name='update_profile_view'),
    url(r'^location/(?P<username>[-_\w.]+)/update/$',
        views.update_location, name='update_location_view'),
    url(r'^find_passenger/$', views.find_passenger, name='find_passenger'),
    url(r'^add-marker/$', views.add_marker, name='add_marker'),
    url(r'^comment/$', views.add_comment, name='add_comment'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

car/driver/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


class DriverProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(
        upload_to='profile/driver/', default='/media/profile/driver/user.svg', null=True)
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, null=True)
    car_capacity = models.IntegerField(null=True)
    plates = models.CharField(max_length=30, null=True)
    car_color = models.CharField(max_length=30, null=True)

    def getPic(self):
        if not self.profile_pic:
            return '/media/profile/driver/user.svg'

    # link to in-built user model
    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            DriverProfile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.driverprofile.save()
    # end of link


class CarPool(models.Model):
    name = models.CharField(max_length=50, blank=True)
    destination = models.CharField(max_length=100, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Location(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='driver_location')
    current = models.CharField(max_length=100, blank=True)
    destination = models.CharField(max_length=100, blank=True)

    # link to in-built user model
    @receiver(post_save, sender=User)
    def create_user_location(sender, instance, created, **kwargs):
        if created:
            Location.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_location(sender, instance, **kwargs):
        instance.driver_location.save()
    # end of link


class Reviews(models.Model):
    review = models.TextField(blank=True)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='driver_reviews')

car/driver/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import DriverProfile, CarPool, Location, Reviews


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']


class DriverProfileForm(forms.ModelForm):
    class Meta:
        model = DriverProfile
        fields = ['profile_pic', 'gender',
                  'car_capacity', 'plates', 'car_color']


class CarPoolForm(forms.ModelForm):
    class Meta:
        model = CarPool
        fields = ['name', 'destination']

car/driver/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.views.generic import View
from django.contrib import messages
rom django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from .models import DriverProfile, CarPool, Location, Reviews
from passenger.models import PassengerProfile
from .forms import UserForm, DriverProfileForm, LocationForm, CarPoolForm


# Create your views here.


def home(request, username):
    user = User.objects.get(username=username)
    driver_profile = DriverProfile.objects.get(user=user)
    carpool = CarPool.objects.filter(id=user.id)
    num_passengers = len(carpool)
    capacity = driver_profile.car_capacity
    print(carpool)
    print(num_passengers)
    if request.method == 'POST':
        carpool_form = CarPoolForm(request.POST)

        if carpool_form.is_valid() and num_passengers <= capacity:
            carpool_form.save()
            messages.success(request, ('You have a ride with this driver!'))
            return HttpResponseRedirect("/driver/%s" % user.username)
        else:
            messages.error(request, ('This car is full, try another driver.'))
    else:
        carpool_form = CarPoolForm()

    title = 'Driver'
    return render(request, 'driver/home.html', {'title': title, "user": user, "carpool": carpool, "form": carpool_form})


def profile(request, username):
    '''
    render driver information
    '''
    user = User.objects.get(username=username)
    profile = DriverProfile.objects.get(user=user)
    location = Location.objects.get(user=user)

    title = f"{user.username}"
    return render(request, 'driver/profile.html', {"user": user, "profile": profile, "location": location})


def update_profile(request, username):
    user = User.objects.get(username=username)
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = DriverProfileForm(
            request.POST, instance=request.user.driverprofile, files=request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(
                request, ('Your profile was successfully updated!'))
            return HttpResponseRedirect("/driver/profile/%s" % user.username)
        else:
            messages.error(request, ('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = DriverProfileForm(instance=request.user.driverprofile)
    return render(request, 'driver/update_profile.html', {"user_form": user_form, "profile_form": profile_form})


def update_location(request, username):
    user = User.objects.get(username=username)

    if request.method == 'POST':
        location_form = LocationForm(
            request.POST, instance=request.user.driver_location)
        print(location_form)
        if location_form.is_valid():
            location_form.save()
            messages.success(request, ('You have updated your location.'))
            return HttpResponseRedirect("/driver/profile/%s" % user.username)
        else:
            messages.error(request, ('Please correct the error.'))
    else:
        location_form = LocationForm(instance=request.user.driver_location)

    title = 'Update Location'
    return render(request, 'driver/update_location.html', {"title": title, "form": location_form})


def find_passenger(request):
    passengers = PassengerProfile.objects.all()

    title = 'Find Passenger'
    return render(request, 'passenger/find_passenger.html', {"title": title, "passengers": passengers})


def driver_profile(request, passenger_id):
    user = User.objects.get(id=passenger_id)
    passenger_profile = PassengerProfile.objects.filter(user=user)

    title = 'Passenger Profile'
    return render(request, 'driver/passenger_profile.html', {"title": title, "profile": passenger_profile})

car/driver/templates/driver/driver_base.html
{% load bootstrap3 %} {% load static %}

<!DOCTYPE html>
<html>

 <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1"> {% if title %}

  <title>{{title}}</title>

  {% endif %} {% block styles %} {% bootstrap_css %}
  <link rel="stylesheet" href="{% static 'css/driver.css' %}" /> {% endblock %}

 </head>

 <body>
  <div class="container-fluid">
   {% include 'driver/driver_sidenav.html'%} {% block content %} {% endblock %}
  </div>

  {% block scripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% bootstrap_javascript %}
  <script src="https://use.fontawesome.com/b0e34048aa.js"></script>
  <!-- <script src="{% static 'js/driver.js' url%}"></script> -->
  <script src="{% static 'js/ajax_tokens.js' url%}"></script>
  <script src="{% static 'js/marker-map.js' url%}"></script>
  <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDdHoyRN24loeP8pO0iSo6kMRPd5CbfrWA&callback=initMap" type="text/javascript"></script>
  {% endblock %}

 </body>

</html>

car/driver/templates/driver/driver_sidenav.html
{% load bootstrap3 %} {% load static %}

<!DOCTYPE html>
<html>

 <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
 </head>

 <body>

  <div class="col-md-3 col-lg-3">
   <h1>Driver</h1>
   <div class="links">
    <ul>
     <li><a href="{% url 'driver:home' user.username %}"><span class="fa fa-home"></span><h4>Home</h4></a></li>
     <li> <a href="{% url 'driver:profile_view' user.username %}"><span class="fa fa-user"></span> <h4>Profile</h4></a> </li>
     <li><a href="{% url 'driver:find_passenger' %}"><span class="fa fa-search"></span> <h4>Find Passenger</h4></a></li>
     <li><a href="{% url 'driver:add_marker' %}"><span class="fa fa-map-marker"></span> <h4>Add Pick Up Location</h4></a></li>
     <li><a href="/"><span class="fa fa-sign-out"></span> <h4>Logout</h4></a></li>
    </ul>
   </div>
  </div>

 </body>

</html>

car/driver/templates/driver/find_passangers.html
{% extends 'passenger/pass_base.html' %} {% load bootstrap3 %} {% block content %}
<div class="col-md-7 col-lg-7">
 <h3>Find Passengers</h3> {% for passenger in passengers %} {% if user != passenger.user %} {% if passenger.profile_pic %}
 <img src="{{passenger.profile_pic.url}}" alt="User PPic"> {% else %}
 <img src="passenger.getImage" alt="Avatar"> {% endif %}
 <h4>{{passenger.user.first_name}} {{passenger.user.last_name}}</h4>
 <a href="{% url 'driver:passenger_profile' passenger.user.id %}" class="btn btn-info btn-lg">View Profile</a>
 <hr> {% endif %} {% endfor %}
</div>
{% endblock %}

car/driver/templates/driver/passanger_profile.html
{% extends 'passenger/pass_base.html' %} {% load bootstrap3 %} {% load static %} {% block content %}
<div class="col-md-7 col-lg-7 view-update">
 {% for profile in profile %}
 <h3>{{profile.user.first_name}}'s Profile</h3>

 <div class="passenger-details">
  {% if profile.profile_pic %}
  <img src="{{profile.profile_pic.url}}" alt="User PPic"> {% else %}
  <img src="profile.getImage" alt="Avatar"> {% endif %}
  <h4>First Name</h4>
  <h5>{{profile.user.first_name}}</h5>
  <h4>Last Name</h4>
  <h5>{{profile.user.last_name}}</h5>
  <hr>


  <h3>Location:</h3>
  <h4>Current Location</h4>
  <h5>{{location.current}}</h5>
  <h4>Destination</h4>
  <h5>{{location.destination}}</h5> {% if not profile.user %}
  <h4>Email</h4> <em><h5>Email is hidden</h5></em> {% else %}
  <h4>Email</h4> <em><h5>{{profile.user.email}}</h5></em> {% endif %}
  <hr>
  <h4>Gender</h4>
  <h5>{{profile.gender}}</h5>
  <hr>
  <h4>Vehicle:</h4>
  <h4>Car Capacity</h4>
  <h5>{{profile.car_capacity}}</h5>
  <h4>Car Plates</h4>
  <h5>{{profile.plates}}</h5>
  <h4>Car Color</h4>
  <h5>{{profile.car_color}}</h5>
  <ul class="comment-list">
   <li class="comment-list__comment">
    {{ profile.user.username }}
    <span class="comment">{{ profile.user.email }}</span>
   </li>
   {% for comment in post.comment_set.all %}
   <li class="comment-list__comment">
    <a href="{% url 'profile' comment.user.username %}" class="user">
                        {{ comment.user.username }}
                    </a>
    <span class="comment">{{ comment.comment }}</span>
   </li>
   {% endfor %}
  </ul>
  <section class="input-row">
   <div class="comment-input-wrapper">
    <input class="add-comment" type="text" placeholder="Add a comment...">
   </div>
   <div class="hidden-data {{ passenger.id }}" style="display: none;">
    <span class="passenger_id">{{ profile.user.id }}</span>
   </div>
  </section>

 </div>

 {% endfor %}
</div>
{% endblock%}

car/driver/templates/driver/pick_up.html
{% extends 'driver/driver_base.html' %} {% load bootstrap3 %} {% block content %}
<div class="col-md-7 col-lg-7 map-container">
 <h3>Set pick up points</h3>
 <div id="marker-map">

 </div>

</div>
{% endblock %}

car/driver/templates/driver/profile.html
{% extends 'driver/driver_base.html' %} {% load bootstrap3 %} {% load static %} {% block content %}
<div class="col-md-7 col-lg-7">
 <h3>{{user.first_name}}'s Profile</h3>

 <div class="driver-details">
  <div class="col-md-6 col-lg-6">

   {% if profile.profile_pic %}
   <img src="{{profile.profile_pic.url}}" alt="User PPic"> {% else %}
   <img src="profile.getImage" alt="Avatar"> {% endif %}

   <h4>First Name</h4>
   <h5>{{profile.user.first_name}}</h5>
   <h4>Last Name</h4>
   <h5>{{profile.user.last_name}}</h5>
   <hr>

   <h3>Location:</h3>
   <h4>Current Location</h4>
   <h5>{{location.current}}</h5>
   <h4>Destination</h4>
   <h5>{{location.destination}}</h5> {% if user %}
   <a href="{% url 'driver:update_location_view' user.username %}" class="btn btn-info btn-sm">Update Location</a> {% else %}
   <a href="{% url 'driver:update_location_view' user.username %}" style="display:none"></a> {% endif %} {% if not user %}
   <h4>Email</h4> <em><h5>Email is hidden</h5></em> {% else %}
   <h4>Email</h4> <em><h5>{{profile.user.email}}</h5></em> {% endif %}
   <hr>
   <h4>Gender</h4>
   <h5>{{profile.gender}}</h5>
   <hr>

   <h4>Vehicle:</h4>
   <h4>Car Capacity</h4>
   <h5>{{profile.car_capacity}}</h5>
   <h4>Car Plates</h4>
   <h5>{{profile.plates}}</h5>
   <h4>Car Color</h4>
   <h5>{{profile.car_color}}</h5>
  </div>
  <a href="{% url 'driver:update_profile_view' request.user.username %}"><span class="fa fa-pencil"></span><h4>Update Profile</h4></a>

 </div>

</div>
{% endblock%}

car/driver/templates/driver/update_location.html
{% extends "driver/driver_base.html" %} {% load bootstrap3 %} {% block content %}
<div class="col-md-7 col-lg-7">
 <div class="row">
  <!-- Empty div -->
  <div class="col-md-3"></div>
  <div class="col-md-6">
   {% if form.errors %}
   <p> Some Information Might be Incorrect </p>
   {% endif %}
   <div class="panel panel-default">

    <div class="panel-heading">
     <h3 class="text-center">Update Location</h3>
    </div>
    <div class="panel-body">

     <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %} {% bootstrap_form form %}

      <div class="form-group">
       <input type="submit" class="btn btn-primary btn-sm" value="Update Profile">
      </div>

      <input type="hidden" name="next" value="{{next}}">

     </form>
    </div>

   </div>
  </div>
  <!-- empty div -->
  <div class="col-md-3"></div>
 </div>
</div>

{% endblock %}

car/driver/templates/driver/update_profile.html
{% extends "driver/driver_base.html" %} {% load bootstrap3 %} {% block content %}
<div class="container">
 <div class="row">
  <!-- Empty div -->
  <div class="col-md-3"></div>
  <div class="col-md-6">
   {% if form.errors %}
   <p> Some Information Might be Incorrect </p>
   {% endif %}
   <div class="panel panel-default">

    <div class="panel-heading">
     <h3 class="text-center">Update Profile</h3>
    </div>
    <div class="panel-body">

     <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %} {% bootstrap_form user_form %} {% bootstrap_form profile_form %}
      <div class="form-group">
       <input type="submit" class="btn btn-primary btn-sm" value="Update Profile">
      </div>

      <input type="hidden" name="next" value="{{next}}">

     </form>

     <em class="auth-redir">Already have an account? <a href="/">Sign in to App</a></em>
    </div>

   </div>

  </div>
  <!-- empty div -->
  <div class="col-md-3"></div>
 </div>
</div>

{% endblock %}